/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CommunityPortalsRouteImport } from './routes/community-portals'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CPortalSlugRouteImport } from './routes/c.$portalSlug'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as CPortalSlugTrialsRouteImport } from './routes/c.$portalSlug.trials'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'
import { Route as CPortalSlugTrialsIndexRouteImport } from './routes/c.$portalSlug.trials.index'
import { Route as CPortalSlugTrialsTriallSlugEventsRouteImport } from './routes/c.$portalSlug.trials.$triallSlug.events'
import { Route as CPortalSlugTrialsTriallSlugDashboardRouteImport } from './routes/c.$portalSlug.trials.$triallSlug.dashboard'

const CommunityPortalsRoute = CommunityPortalsRouteImport.update({
  id: '/community-portals',
  path: '/community-portals',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CPortalSlugRoute = CPortalSlugRouteImport.update({
  id: '/c/$portalSlug',
  path: '/c/$portalSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CPortalSlugTrialsRoute = CPortalSlugTrialsRouteImport.update({
  id: '/trials',
  path: '/trials',
  getParentRoute: () => CPortalSlugRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CPortalSlugTrialsIndexRoute = CPortalSlugTrialsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CPortalSlugTrialsRoute,
} as any)
const CPortalSlugTrialsTriallSlugEventsRoute =
  CPortalSlugTrialsTriallSlugEventsRouteImport.update({
    id: '/$triallSlug/events',
    path: '/$triallSlug/events',
    getParentRoute: () => CPortalSlugTrialsRoute,
  } as any)
const CPortalSlugTrialsTriallSlugDashboardRoute =
  CPortalSlugTrialsTriallSlugDashboardRouteImport.update({
    id: '/$triallSlug/dashboard',
    path: '/$triallSlug/dashboard',
    getParentRoute: () => CPortalSlugTrialsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/community-portals': typeof CommunityPortalsRoute
  '/api/$': typeof ApiSplatRoute
  '/c/$portalSlug': typeof CPortalSlugRouteWithChildren
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/c/$portalSlug/trials': typeof CPortalSlugTrialsRouteWithChildren
  '/c/$portalSlug/trials/': typeof CPortalSlugTrialsIndexRoute
  '/c/$portalSlug/trials/$triallSlug/dashboard': typeof CPortalSlugTrialsTriallSlugDashboardRoute
  '/c/$portalSlug/trials/$triallSlug/events': typeof CPortalSlugTrialsTriallSlugEventsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community-portals': typeof CommunityPortalsRoute
  '/api/$': typeof ApiSplatRoute
  '/c/$portalSlug': typeof CPortalSlugRouteWithChildren
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/c/$portalSlug/trials': typeof CPortalSlugTrialsIndexRoute
  '/c/$portalSlug/trials/$triallSlug/dashboard': typeof CPortalSlugTrialsTriallSlugDashboardRoute
  '/c/$portalSlug/trials/$triallSlug/events': typeof CPortalSlugTrialsTriallSlugEventsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/community-portals': typeof CommunityPortalsRoute
  '/api/$': typeof ApiSplatRoute
  '/c/$portalSlug': typeof CPortalSlugRouteWithChildren
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/c/$portalSlug/trials': typeof CPortalSlugTrialsRouteWithChildren
  '/c/$portalSlug/trials/': typeof CPortalSlugTrialsIndexRoute
  '/c/$portalSlug/trials/$triallSlug/dashboard': typeof CPortalSlugTrialsTriallSlugDashboardRoute
  '/c/$portalSlug/trials/$triallSlug/events': typeof CPortalSlugTrialsTriallSlugEventsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/community-portals'
    | '/api/$'
    | '/c/$portalSlug'
    | '/api/rpc/$'
    | '/c/$portalSlug/trials'
    | '/c/$portalSlug/trials/'
    | '/c/$portalSlug/trials/$triallSlug/dashboard'
    | '/c/$portalSlug/trials/$triallSlug/events'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/community-portals'
    | '/api/$'
    | '/c/$portalSlug'
    | '/api/rpc/$'
    | '/c/$portalSlug/trials'
    | '/c/$portalSlug/trials/$triallSlug/dashboard'
    | '/c/$portalSlug/trials/$triallSlug/events'
  id:
    | '__root__'
    | '/'
    | '/community-portals'
    | '/api/$'
    | '/c/$portalSlug'
    | '/api/rpc/$'
    | '/c/$portalSlug/trials'
    | '/c/$portalSlug/trials/'
    | '/c/$portalSlug/trials/$triallSlug/dashboard'
    | '/c/$portalSlug/trials/$triallSlug/events'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommunityPortalsRoute: typeof CommunityPortalsRoute
  ApiSplatRoute: typeof ApiSplatRoute
  CPortalSlugRoute: typeof CPortalSlugRouteWithChildren
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/community-portals': {
      id: '/community-portals'
      path: '/community-portals'
      fullPath: '/community-portals'
      preLoaderRoute: typeof CommunityPortalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$portalSlug': {
      id: '/c/$portalSlug'
      path: '/c/$portalSlug'
      fullPath: '/c/$portalSlug'
      preLoaderRoute: typeof CPortalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$portalSlug/trials': {
      id: '/c/$portalSlug/trials'
      path: '/trials'
      fullPath: '/c/$portalSlug/trials'
      preLoaderRoute: typeof CPortalSlugTrialsRouteImport
      parentRoute: typeof CPortalSlugRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$portalSlug/trials/': {
      id: '/c/$portalSlug/trials/'
      path: '/'
      fullPath: '/c/$portalSlug/trials/'
      preLoaderRoute: typeof CPortalSlugTrialsIndexRouteImport
      parentRoute: typeof CPortalSlugTrialsRoute
    }
    '/c/$portalSlug/trials/$triallSlug/events': {
      id: '/c/$portalSlug/trials/$triallSlug/events'
      path: '/$triallSlug/events'
      fullPath: '/c/$portalSlug/trials/$triallSlug/events'
      preLoaderRoute: typeof CPortalSlugTrialsTriallSlugEventsRouteImport
      parentRoute: typeof CPortalSlugTrialsRoute
    }
    '/c/$portalSlug/trials/$triallSlug/dashboard': {
      id: '/c/$portalSlug/trials/$triallSlug/dashboard'
      path: '/$triallSlug/dashboard'
      fullPath: '/c/$portalSlug/trials/$triallSlug/dashboard'
      preLoaderRoute: typeof CPortalSlugTrialsTriallSlugDashboardRouteImport
      parentRoute: typeof CPortalSlugTrialsRoute
    }
  }
}

interface CPortalSlugTrialsRouteChildren {
  CPortalSlugTrialsIndexRoute: typeof CPortalSlugTrialsIndexRoute
  CPortalSlugTrialsTriallSlugDashboardRoute: typeof CPortalSlugTrialsTriallSlugDashboardRoute
  CPortalSlugTrialsTriallSlugEventsRoute: typeof CPortalSlugTrialsTriallSlugEventsRoute
}

const CPortalSlugTrialsRouteChildren: CPortalSlugTrialsRouteChildren = {
  CPortalSlugTrialsIndexRoute: CPortalSlugTrialsIndexRoute,
  CPortalSlugTrialsTriallSlugDashboardRoute:
    CPortalSlugTrialsTriallSlugDashboardRoute,
  CPortalSlugTrialsTriallSlugEventsRoute:
    CPortalSlugTrialsTriallSlugEventsRoute,
}

const CPortalSlugTrialsRouteWithChildren =
  CPortalSlugTrialsRoute._addFileChildren(CPortalSlugTrialsRouteChildren)

interface CPortalSlugRouteChildren {
  CPortalSlugTrialsRoute: typeof CPortalSlugTrialsRouteWithChildren
}

const CPortalSlugRouteChildren: CPortalSlugRouteChildren = {
  CPortalSlugTrialsRoute: CPortalSlugTrialsRouteWithChildren,
}

const CPortalSlugRouteWithChildren = CPortalSlugRoute._addFileChildren(
  CPortalSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommunityPortalsRoute: CommunityPortalsRoute,
  ApiSplatRoute: ApiSplatRoute,
  CPortalSlugRoute: CPortalSlugRouteWithChildren,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
